version: '3.8'

services:
  db_apotek:
    image: mysql:8
    container_name: db_apotek
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bookselfpakemas1223
      MYSQL_DATABASE: apotek_db
    ports:
      - "3307:3306"
    volumes:
      - apotek_data:/var/lib/mysql

  db_hospital:
    image: mysql:8
    container_name: db_hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bookselfpakemas1223
      MYSQL_DATABASE: hospital_db
    ports:
      - "3308:3306"
    volumes:
      - hospital_data:/var/lib/mysql

  apotek:
    build: ./ApotekService
    container_name: apotek_service
    ports:
      - "8002:80"
    depends_on:
      - db_apotek

  hospital:
    build: ./HospitalService
    container_name: hospital_service
    ports:
      - "8001:80"
    depends_on:
      - db_hospital

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8000:80"
    depends_on:
      - apotek
      - hospital

volumes:
  apotek_data:
  hospital_data:
