version: '3.8'

networks:
  backend_net:
    driver: bridge

services:
  db_apotek:
    image: mysql:8
    container_name: db_apotek
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: apotek_db
    ports:
      - "3307:3306"
    volumes:
      - apotek_data:/var/lib/mysql
    networks:
      - backend_net

  db_hospital:
    image: mysql:8
    container_name: db_hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: hospital_db
    ports:
      - "3308:3306"
    volumes:
      - hospital_data:/var/lib/mysql
    networks:
      - backend_net

  apotek:
    build: ./ApotekService
    container_name: apotek_service
    ports:
      - "8002:80"
    depends_on:
      - db_apotek
    networks:
      - backend_net

  hospital:
    build: ./HospitalService
    container_name: hospital_service
    ports:
      - "8001:80"
    depends_on:
      - db_hospital
    networks:
      - backend_net

  frontend:
    build: ./fe
    container_name: frontend_service
    ports:
      - "8000:80"
    depends_on:
      - apotek
      - hospital
    networks:
      - backend_net

volumes:
  apotek_data:
  hospital_data:
